name: fcc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_background: ^2.0.0
  flutter:
    sdk: flutter
  package_info_plus: ^8.1.1
  flutter_pdfview: ^1.3.4
  syncfusion_flutter_pdfviewer: ^28.1.35
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
